### ISSUE TITLE
usb问题会导致什么功能没法使用啊？

### ISSUE THREAD

**Issue by jk110** [extremegrief1/Lenovo_Legion_5_Hackintosh#1]
大佬这个usb问题会导致什么功能没法使用啊，直接用你这个ufi就可以安装12.6了吗，你说的安装要重启几十次才会成功和会异常关机还存在不

**Comment by extremegrief1** [comment]
> 大佬这个usb问题会导致什么功能没法使用啊，直接用你这个ufi就可以安装12.6了吗，你说的安装要重启几十次才会成功和会异常关机还存在不

English please...

**Comment by jk110** [comment]
Can the EFI install the mac os normally? Will the problem that you said you need to restart dozens of times to install it occur? How about the stability? Thank you

**Comment by jk110** [comment]
USB storage cannot be used? How to install the mac os

**Comment by zty199** [comment]
> USB storage cannot be used? How to install the mac os

[zxc2689963](https://forum.amd-osx.com/members/zxc2689963.15444/) is not here......

As zxc2689963 says, if you want to install Monterey using USB installer, you should disable GenericUSBXHCI.kext in config.plist. However, the process may still be sufferring...... See in this [reply](https://forum.amd-osx.com/threads/amd-rayon-r7-5800h-install-monterey-kernel-panic.2725/post-21929).

For now I will suggest you installing monterey from another PC into your drive, and then install the drive to your Legion 5......
---
[zxc2689963](https://forum.amd-osx.com/members/zxc2689963.15444/) 大佬不在这个仓库......

按照大佬的[回复](https://forum.amd-osx.com/threads/amd-rayon-r7-5800h-install-monterey-kernel-panic.2725/post-21929)，通过 U盘 安装不能使用 GenericUSBXHCI.kext。但是会导致大概率在引导时卡在 PCI Configuration End 后面，目前无解。

暂时还是建议在其他电脑上安装 Monterey 到你的硬盘上，然后再把硬盘装回拯救者......（前提是你有别的黑苹果机器能稳定使用......）

**Comment by jk110** [comment]
感谢解答
