### ISSUE TITLE
Unable to start using this efi. Please help me to see if there is a problem with the bios settings. Thank you

### ISSUE THREAD

**Issue by jk110** [extremegrief1/Lenovo_Legion_5_Hackintosh#2]
@zty199 感谢
![微信图片_20221010204653](https://user-images.githubusercontent.com/56330712/194869875-fbb327b3-8ef6-4ea4-a5b2-5830f700a9d5.jpg)
![微信图片_202210102046531](https://user-images.githubusercontent.com/56330712/194869888-7789ee49-f848-4a46-8fdb-677ea468eecd.jpg)
![微信图片_202210102046532](https://user-images.githubusercontent.com/56330712/194869892-3e9a60cf-7d71-49d0-a8ef-f7a15459805b.jpg)
![微信图片_202210102046533](https://user-images.githubusercontent.com/56330712/194869894-cbec11b2-6be4-4936-9bc6-01ebec108dd7.jpg)
![微信图片_202210102046534](https://user-images.githubusercontent.com/56330712/194869900-3391b60b-8346-4295-8445-e6bd26c91d76.jpg)
![微信图片_202210102046535](https://user-images.githubusercontent.com/56330712/194869907-75333cf3-68b6-4597-82e8-9cbde6cc2f25.jpg)

**Comment by jk110** [comment]
The phenomenon is running code and then restarting

**Comment by jk110** [comment]
[Uploading video.zip…]()

https://user-images.githubusercontent.com/56330712/194874814-c70b5cda-348b-4ccf-98f6-5c0f1e4ce16f.mp4

**Comment by jk110** [comment]
My configuration is a MediaTek network card. The pm8512 is solid. Everything else is the same. I installed the macos on another computer: macOS Monterey 12.6. Do I have problems upgrading to it.

我的配置是联发科网卡，pm8512固态，其他都一样，macos是我在另一台电脑上装好的：macOS Monterey 12.6，我是升级上去的这样会有问题吗。

**Comment by jk110** [comment]
Need to update the bios version to the latest
bios版本需要更新到最新吗

**Comment by jk110** [comment]
![8801c067f837dd71deecb910562c2c3](https://user-images.githubusercontent.com/56330712/194981311-b6188d93-0772-40cf-923b-a63ddbcafe3a.jpg)

![ec89d79bcb22704108fd153a891c440](https://user-images.githubusercontent.com/56330712/194981328-f3d1618e-461d-4b1d-86a2-99ae796323b1.jpg)

![5f9892b717eba29c1871de7201b56e3](https://user-images.githubusercontent.com/56330712/194981341-d0cc7a13-9ecf-4db6-9231-c498ac9ac06b.jpg)

![9d7350c3c07a1aa570ba95f84cbe9a6](https://user-images.githubusercontent.com/56330712/194981357-d2870991-9d5e-45cf-8177-2866d1443667.jpg)

![bb0585fb40bf88e3cca181b7e22e3fb](https://user-images.githubusercontent.com/56330712/194981379-a8f1bc27-8053-464f-9191-35cbe9e8994d.jpg)

![7403c32a142c593bb9d6e0130c7e11b](https://user-images.githubusercontent.com/56330712/194981417-2d1638a5-810d-4d35-b604-25dedc5097b0.jpg)

**Comment by jk110** [comment]
![8801c067f837dd71deecb910562c2c3](https://user-images.githubusercontent.com/56330712/194981716-0eea5ebe-fb70-442a-8c5a-ddca1c9c9fb3.jpg)
![ec89d79bcb22704108fd153a891c440](https://user-images.githubusercontent.com/56330712/194981731-f192b1d8-a387-4028-9a63-ba1edd4ca3cb.jpg)
![5f9892b717eba29c1871de7201b56e3](https://user-images.githubusercontent.com/56330712/194981741-e1b86668-e4df-45d2-a78b-dc66b80d319e.jpg)
![9d7350c3c07a1aa570ba95f84cbe9a6](https://user-images.githubusercontent.com/56330712/194981750-46609751-435e-413f-80b5-94fc3dbf3a78.jpg)
![bb0585fb40bf88e3cca181b7e22e3fb](https://user-images.githubusercontent.com/56330712/194981760-ca13822b-2d2f-46b3-b8e8-3c555ae953a7.jpg)
![7403c32a142c593bb9d6e0130c7e11b](https://user-images.githubusercontent.com/56330712/194981772-b651938d-27b7-458c-bf7c-fdd9e6ddceee.jpg)

**Comment by jk110** [comment]
![image](https://user-images.githubusercontent.com/56330712/194982054-37dd8262-c3db-46f7-90bf-dec997eddd0c.png)

**Comment by jk110** [comment]
![image](https://user-images.githubusercontent.com/56330712/194990379-75a16fb3-8489-4451-b060-cad7a1af3bec.png)

**Comment by jk110** [comment]
os
![d21158ce7871d9ab8b1eb6352af67ba](https://user-images.githubusercontent.com/56330712/195014204-b5083a34-6f9e-4628-b325-73abc0603c32.png)

**Comment by jk110** [comment]
os
![d21158ce7871d9ab8b1eb6352af67ba](https://user-images.githubusercontent.com/56330712/195014294-1dcda0ea-d557-4f53-a6b5-43e87a6f92e8.png)

**Comment by jk110** [comment]
Changing the hard disk to: WDSN550 also fails

**Comment by zty199** [comment]
You have to remove your original Hynix PC711 NVMe drive, seems that it doesn't work on macOS...... See in this [reply](https://forum.amd-osx.com/threads/amd-rayon-r7-5800h-install-monterey-kernel-panic.2725/post-21923).

---
你需要把原装的海力士 512G 的固态拆掉，macOS [不支持这个主控，会导致无法启动。可以看这条[回复](https://forum.amd-osx.com/threads/amd-rayon-r7-5800h-install-monterey-kernel-panic.2725/post-21923)。
>P.S. 目前联想美国官网倒是有固态的固件升级，然而很不巧的是国行预装的这款固态序列号和美行的不一样，没法升级固件。所以暂时无解了......

**Comment by jk110** [comment]
@zty199 兄弟，我的bios设置没问题把

**Comment by extremegrief1** [comment]
English....

**Comment by jk110** [comment]
我的触摸板和声卡没有正常工作

My touch pad and sound card are not working properly

**Comment by jk110** [comment]
When the layout id is 21, there is sound

**Comment by jk110** [comment]
When the "layout-id" is 21, there is sound

**Comment by zty199** [comment]
> When the "layout-id" is 21, there is sound

OK, I will update config.plist when I'm free. About touchpad, VoodooI2C is not compatible with AMD I2C controller for now......

---
感谢，有空我会更新下 EFI 的设备属性配置的。目前 VoodooI2C 好像还不支持 AMD 的 I2C 控制器，所以触摸板应该暂时无解了......
